site_name: Ktorfit
repo_name: Ktorfit

repo_url: https://github.com/Foso/Ktorfit
site_url: https://github.com/Foso/Ktorfit
docs_dir: 'docs'
edit_uri: 'tree/master/docs/'

# Copyright
copyright: Copyright &copy; Apache v2 License 2022-2024 Jens Klingenberg
extra:
  manifest: manifest.webmanifest
  site:
    images: '../../images'
  ktorfit:
    release: "2.2.0"
  ktor:
    release: "3.0.1"
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/foso'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/jklingenberg_'
    - icon: fontawesome/solid/arrow-up-right-from-square
      link: 'https://jensklingenberg.de/'
theme:
  name: 'material'
  language: en
  custom_dir: 'docs/theme'
  font:
    text: Ubuntu
    code: Jetbrains Mono
  features:
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.share
  palette:
    - scheme: default
      primary: deep-blue
      accent: deep-purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: fontawesome/solid/code
    repo: fontawesome/brands/github
nav:
  - 'Overview': index.md
  - 'Quick start': quick-start.md
  - 'Installation': installation.md
  - 'Requests': requests.md
  - 'Converters':
      - 'Converters': converters/converters.md
      - 'ResponseConverter': converters/responseconverter.md
      - 'SuspendResponseConverter': converters/suspendresponseconverter.md
      - 'RequestParameterConverter' : converters/requestparameterconverter.md
      - 'Example1': converters/example1.md
      - 'Migration': converters/migration.md
  - 'Configuration': configuration.md
  - 'Android':
      - 'proguard': android/proguard.md
  - 'Known issues': knownissues.md
  - 'Fundamentals' :
      - 'Scope' : fundamentals/scope.md
      - 'Architecture': architecture.md
  - 'Migration': migration.md
  - 'Changelog': CHANGELOG.md
  - 'License': License.md
markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji
  - tables
  - admonition

plugins:
  - macros
  - search
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
