[versions]
abg= "8.2.2"
autoService = "1.1.1"
binaryCompatibilityValidator = "0.16.3"
coroutines = "1.8.1"
detekt = "1.23.7"
junit = "4.13.2"
kctfork = "0.5.1"
kotlin = "2.0.21"
kotlinPoet = "1.18.1"
kspVersion = "2.0.21-1.0.27"

groupId = "de.jensklingenberg.ktorfit"
ktorfit = "2.2.0"
ktorfitKsp = "2.2.0-1.0.27"
ktorfitCompiler = "2.1.0-2.0.21"
ktorfitCallConverter = "2.2.0"
ktorfitFlowConverter = "2.2.0"
ktorfitResponseConverter = "2.2.0"
ktorfitGradle = "2.2.0"

ktorfitGradlePlugin = "2.1.0"
ktorVersion = "3.0.1"
mockk = "1.13.13"
mockito-kotlin = "4.1.0"
gradleMavenPublishPlugin = "0.28.0"
vannikMavenPublish = "0.28.0"

[libraries]
android-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "abg" }
autoService = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
gradle-maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradleMavenPublishPlugin" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
ktorfit-gradle-plugin = { module = "de.jensklingenberg.ktorfit:ktorfit-gradle-plugin", version.ref = "ktorfitGradlePlugin" }
junit = { module = "junit:junit", version.ref = "junit" }
kctfork-core = { module = "dev.zacsweers.kctfork:core", version.ref = "kctfork" }
kctfork-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "kctfork" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kotlinPoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-runtime-js = "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:0.20.0"
kspApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "kspVersion" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

#Ktor
ktor-client-cio-jvm = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktorVersion" }
ktor-client-cio-linuxX64 = { module = "io.ktor:ktor-client-cio-linuxx64", version.ref = "ktorVersion" }
ktor-client-cio-linuxArm64 = { module = "io.ktor:ktor-client-cio-linuxarm64", version.ref = "ktorVersion" }

ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-client-core-jvm = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktorVersion" }
ktor-client-core-linuxX64 = { module = "io.ktor:ktor-client-core-linuxx64", version.ref = "ktorVersion" }
ktor-client-core-linuxArm64 = { module = "io.ktor:ktor-client-core-linuxarm64", version.ref = "ktorVersion" }

ktor-client-core-mingwx64 = { module = "io.ktor:ktor-client-core-mingwx64", version.ref = "ktorVersion" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktorVersion" }
ktor-client-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktorVersion" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktorVersion" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorVersion" }
ktor-client-json-js = { module = "io.ktor:ktor-client-json-js", version.ref = "ktorVersion" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorVersion" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktorVersion" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktorVersion" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktorVersion" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }

licensee-gradle-plugin = "app.cash.licensee:licensee-gradle-plugin:1.12.0"
logbackClassic = "ch.qos.logback:logback-classic:1.5.6"
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vannikMavenPublish" }
